site_name: ConnexCS Documentation
site_url: http://www.connexcs.com
site_description: Connex Cloud Softswitch
site_author: ConnexCS Team

extra_javascript:
- extra.js

pages:
- Feature List: feature-list.md
- GETTING STARTED: getting-started.md
- Home: index.md

- CUSTOMERS:
    - Customers: customer.md
    - Credit Control: credit-control.md
    - CLI: cli.md
    - Ingress Routing: ingress-routing.md
    - My Account: my-account.md
    - NAT Traversal: far-end-nat-traversal.md
    - Payments: customer-payments.md
    - Routing Strategy: routing-strategy.md
    - Email Verification: email-verification.md
    - Mobile Verification: mobile-verification.md
