site_name: ConnexCS Documentation
site_url: http://www.connexcs.com
site_description: Connex Cloud Softswitch
site_author: ConnexCS Team

extra_javascript:
- extra.js

pages:
- Home: index.md
- GETTING STARTED: getting-started.md

- CUSTOMER:
    - Customer: customer.md
    - Credit Control: credit-control.md
    - CLI: cli.md
    - Ingress Routing: ingress-routing.md
    - My Account: my-account.md
    - Paypal: customer-payments.md
    - Routing Strategy: routing-strategy.md
    
- CARRIER: 
    - Carrier: carrier.md
    
- CUSTOMER PORTAL:
    - Customer Portal: customer-portal.md

- RATE CARDS:
    - Overview: provider-ratecard.md
    - Provider Ratecard: provider-ratecard.md
    - Customer Ratecard: customer-ratecard.md
    - Building: rate-card-building.md
    - Card Management: card-management.md
    
- DID:
    - DID/Origination: did.md

- MISCELLANENOUS:
    - Authentication: authentication.md
    - Connex Billing: billing.md
    - Calling Card: calling-card.md
    - Files: files.md
    - Feature List: feature-list.md
    - Invoice: invoice.md
    - Capacity Limiting: limiting-cps.md
    - Logging: logging.md
    - Circuit Test: circuit-test.md
    - My Servers: my-servers.md
    - Routing: routing.md
    - Routing USA: routing-usa.md
    - Routing Engine: routing-engine.md
    - Reporting Problems: reporting-problems.md
    - Specification: spec.md
    - Scriptforge: scriptforge.md
    - Scheduled Breakout Reports: scheduled-breakout-reports.md
    - Packages: packages.md
    - User Space Database: user-space-db.md
   
- Report:
    - Breakout Reports: report.md
   
- Architecture:
    - API: api.md
    - NAT Traversal: far-end-nat-traversal.md
    - Security: security.md
    - Media Handling: media-handling.md    
    - Scaling and Load Balancing: scaling-load-balancing.md 
