site_name: ConnexCS Documentation
site_url: https://www.connexcs.com
site_description: Connex Cloud Softswitch
site_author: ConnexCS Team
google_analytics: ['UA-155210453-1', 'docs.connexcs.com']
theme:
  name: material 
  feature:
    tabs: true  
extra_javascript:
- extra.js
- https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
extra_css:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css

#plugins:
#  - markdownmermaid

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
      
pages:
  - Cloudswitch:
    - Home: index.md
    - Getting Started: getting-started.md
    - Video Guide: video-guide.md
    - Dashboard : dashboard.md

    - Customer:
        - Main: customer/main.md
        - Auth: customer/auth.md
        - Routing: customer/routing.md
        - CLI: customer/cli.md
        - Customer: customer/customer.md
        - Payment: customer/payment.md
        - DID: customer/did.md
        - CDR: customer/cdr.md
        - Package: customer/package.md
        - Monitoring: customer/monitoring.md
        - Customer Repository: customer/repository.md
        - 3CX: customer/3cx.md
        - Class5: customer/class5.md
        - Credit Control: customer/credit-control.md


    - Carrier: carrier.md
        
    - Rate Cards:
        - Building Cards: rate-card-building.md
        - Provider Rate Card: provider-ratecard.md
        - Customer Rate Card: customer-ratecard.md

    - Routing:
        - Routing Overview: routing.md
        - Routing Strategy: routing-strategy.md
        - Routing Global: global-routing.md
        - USA Routing: routing-usa.md

    - SIP Devices: sip-devices.md
        
    - DID (Origination): did.md
        
    - Miscellaneous:
        - Authentication: authentication.md
        - Alerts: alert.md
        - Connex Billing: billing.md
        - Calling Card: calling-card.md
        - Circuit Test: circuit-test.md
        - Capacity Limiting: limiting-cps.md
        - Files: files.md
        - Feature List: feature-list.md
        - Invoice: invoice.md
        - Logging: logging.md
        - My Servers: my-servers.md
        - Reporting Problems: reporting-problems.md
        - Specification: spec.md
        - Status: system-status.md  
        - Voucher: voucher.md
        - WebPhone: webphone.md
        - Changing Language: changing-language.md
        - Changing Password: changing-password.md
        - Logging Out: logging-out.md

    - Reports:
        - Breakout Reports: report.md
        - Viewing Audit Logs: viewing-audit-logs.md

    - Class 5:
        - Conference Calling: creating-conference.md
        - IVR: creating-ivr.md
        - Groups: creating-group.md
       
    - Developers:
        - Analytics: developers/analytics.md
        - Database (users): developers/user-space-database.md 
        - Form Builder: developers/form-builder.md
        - ScriptForge Basics: developers/scriptforge.md
        - ScriptForge API: developers/scriptforge-api.md        

    - Setup:
        - AnyEdge: anyedge.md
        - My Account: my-account.md
        - PayPal: customer-payments.md
        - Settings:
            - Account: setup/settings/account.md
            - Payments: setup/settings/payments.md
            - Servers: setup/settings/servers.md
            - DNS: setup/settings/dns.md
            - User: 
                - Creating a User Account: creating-user-account.md
                - Creating a User Group: creating-user-group.md
                - Changing a User's Password: changing-user-password.md
            - Options: setup/settings/options.md
            - Data Retention: setup/settings/data-retention.md
        - Config:
            - Contracts: setup/config/contracts.md
            - Packages: setup/config/packages.md
            - Templates: setup/config/templates.md
            - Analytics: setup/config/analytics.md
        - Advanced:
            - Language: setup/advanced/language.md
            - Firewall: setup/advanced/firewall.md
            - Prefix Set: setup/advanced/prefix-set.md
        - Integrations:
            - API: setup/integrations/api.md
            - Domains: setup/integrations/domains.md
        - Information:
            - Statements: setup/information/statements.md
            - Dial Code / Destination: setup/information/dial-code-destination.md
            - Audit Log: setup/information/audit-log.md
            - Recording: setup/information/recording.md

    - Architecture:
        - API: api.md
        - NAT Traversal: far-end-nat-traversal.md
        - Security: security.md
        - Media Handling: media-handling.md
        - Scaling and Load Balancing: scaling-load-balancing.md

  - AnyEdge: anyedge/anyedge.md

  - Customer Portal:
    - Guides: customer-portal/customer-portal.md
    - Dashboard: customer-portal/dashboard.md
    - CDR: customer-portal/cdr.md
    - Breakout: customer-portal/breakout.md
    - Authentication: customer-portal/authentication.md
    - DID: customer-portal/did.md
    - CLI: customer-portal/cli.md
    - Latest Calls: customer-portal/latest-calls.md
    - Failover: customer-portal/failover.md
    - Setup: customer-portal/setup.md
    - Payment: customer-portal/payment.md
    - Routes: customer-portal/routes.md
    - Interconnect: customer-portal/interconnect.md
