site_name: ConnexCS Documentation
site_url: https://www.connexcs.com
site_description: Connex Cloud Softswitch
site_author: ConnexCS Team
theme:
  name: material 
  feature:
    tabs: true  
extra_javascript:
- extra.js
- https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
extra_css:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css

#plugins:
#  - markdownmermaid

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
      
pages:
  - Cloudswitch:
    - Home: index.md
    - Getting Started: getting-started.md

    - Customer:
        - Main: customer/main.md
        - Auth: customer/auth.md
        - Routing: customer/routing.md
        - CLI: customer/cli.md
        - Customer: customer/customer.md
        - Payment: customer/payment.md
        - Stats: customer/stats.md
        - Route Stats: customer/route-stats.md 
        - Latest-Calls: customer/latest-calls.md
        - Dialogs: customer/dialogs.md
        - Alert: customer/alerts.md
        - Did: customer/did.md
        - Cdr: customer/cdr.md
        - Package: customer/package.md
        - Invoice: customer/invoice.md
        - Contract: customer/contract.md
        - Document: customer/document.md
        - 3CX: customer/3cx.md
        - Class5: customer/class5.md

        - Credit Control: customer/credit-control.md
        - Routing Strategy: customer/routing-strategy.md

    - Carrier: 
        - Carrier: carrier.md
        
    - Rate Cards:
        - Provider Ratecard: provider-ratecard.md
        - Customer Ratecard: customer-ratecard.md
        - Building: rate-card-building.md
        - Card Management: card-management.md
        
    - DID:
        - DID/Origination: did.md
        
    - Micsellanenous:
        - Authentication: authentication.md
        - Connex Billing: billing.md
        - Calling Card: calling-card.md
        - Circuit Test: circuit-test.md
        - Capacity Limiting: limiting-cps.md
        - Files: files.md
        - Feature List: feature-list.md
        - Invoice: invoice.md
        - Logging: logging.md
        - My Servers: my-servers.md
        - Routing: routing.md
        - Routing USA: routing-usa.md
        - Routing Engine: routing-engine.md
        - Reporting Problems: reporting-problems.md
        - Specification: spec.md
        - System Status: system-status.md
        - Changing Language: changing-language.md
        - Changing Password: changing-password.md
        - Logging Out: logging-out.md

    - Reports:
        - Breakout Reports: report.md
        - Viewing Audit Logs: viewing-audit-logs.md

    - Class 5:
        - Creating an IVR Setup: creating-ivr.md
        - Creating a Conference Call: creating-conference.md
        - Creating a Group: creating-group.md
       
    - Developers:
        - Scriptforge: scriptforge.md
        - User Space Database: user-space-db.md 

    - Setup:
        - AnyEdge: anyedge/anyedge.md
        - My Account: my-account.md
        - Paypal: customer-payments.md
        - Settings:
            - Account: setup/settings/account.md
            - Payments: setup/settings/payments.md
            - Servers: setup/settings/servers.md
            - DNS: setup/settings/dns.md
            - User: 
                - Creating a User Account: creating-user-account.md
                - Creating a User Group: creating-user-group.md
                - Changing a User's Password: changing-user-password.md
            - Options: setup/settings/options.md
            - Data Retention: setup/settings/data-retention.md
        - Config:
            - Contracts: setup/config/contracts.md
            - Packages: setup/config/packages.md
            - Templates: setup/config/templates.md
            - Analytics: setup/config/analytics.md
        - Advanced:
            - User Space Database: setup/advanced/user-space-database.md
            - Language: setup/advanced/language.md
            - Firewall: setup/advanced/firewall.md
            - Prefix Set: setup/advanced/prefix-set.md
        - Integrations:
            - API: setup/integrations/api.md
            - Domains: setup/integrations/domains.md
        - Information:
            - Statements: setup/information/statements.md
            - Dial Code / Destination: setup/information/dial-code-destination.md
            - Audit Log: setup/information/audit-log.md
            - Recording: setup/information/recording.md

    - Architecture:
        - API: api.md
        - NAT Traversal: far-end-nat-traversal.md
        - Security: security.md
        - Media Handling: media-handling.md
        - Scaling and Load Balancing: scaling-load-balancing.md
        - Changelog: changelog.md

  - AnyEdge:
    - AnyEdge: anyedge/anyedge.md

  - 3CX:
    - Guides: 3cx/3cx.md

  - Customer Portal:
    - Guides: customer-portal/customer-portal.md
    - Dashboard: customer-portal/dashboard.md
    - CDR: customer-portal/cdr.md
    - Breakout: customer-portal/breakout.md
    - Authentication: customer-portal/authentication.md
    - DID: customer-portal/did.md
    - CLI: customer-portal/cli.md
    - Latest Calls: customer-portal/latest-calls.md
    - Failover: customer-portal/failover.md
    - Setup: customer-portal/setup.md
    - Payment: customer-portal/payment.md
    - Routes: customer-portal/routes.md
    - Interconnect: customer-portal/interconnect.md
