site_name: ConnexCS Documentation
site_url: http://www.connexcs.com
site_description: Connex Cloud Softswitch
site_author: ConnexCS Team

pages:
- Home: index.md
- GETTING STARTED: getting-started.md
- Feature List: feature-list.md

- CUSTOMERS:
    - Customers: customer.md
    - Payments: customer-payments.md
    - Ingress Routing: ingress-routing.md
    - NAT Traversal: far-end-nat-traversal.md
    - Credit Control: credit-control.md
    - Billing: billing.md
    - My Account: my-account.md
 
- CARRIERS: 
    - Carriers: carriers.md

- CARDS:
    - Overview: ratecard.md
    - Generating: rate-card-building.md

- MISCELLANENOUS:
    - Specification: spec.md
    - Authentication: authentication.md
    - Report: report.md
    - Routing: routing.md
    - Routing Engine: routing-engine.md
    - Limiting: limiting-cps.md
    - API: api.md
    - CLI Restriction: cli-restriction.mdcredit-control.md
    - Logging: logging.md
    - Media Handling: media-handling.md
    - Routing Strategy: routing-strategy.md
    - Scaling and Load Balancing: scaling-load-balancing.md 
    - Scriptforge: scriptforge.md
    - SIP Traces: sip-traces.md
