site_name: ConnexCS Documentation
site_url: http://www.connexcs.com
site_description: Connex Cloud Softswitch
site_author: ConnexCS Team

extra_javascript:
- extra.js

pages:
- Home: index.md
- GETTING STARTED: getting-started.md
- Feature List: feature-list.md

- CUSTOMERS:
    - Customers: customer.md
    - Payments: customer-payments.md
    - Ingress Routing: ingress-routing.md
    - NAT Traversal: far-end-nat-traversal.md
    - Credit Control: credit-control.md
    - My Account: my-account.md
    - Routing Strategy: routing-strategy.md
    - CLI Restriction: cli-restriction.md
    - Customer Ratecard: customer-rate-card.md
 
- CARRIERS: 
    - Carriers: carriers.md

- CARDS:
    - Overview: provider-ratecard.md
    - Generating: rate-card-building.md

- DID:
    - DID: did.md

- MISCELLANENOUS:
    - Specification: spec.md
    - Authentication: authentication.md
    - Report: report.md
    - Routing: routing.md
    - Routing Engine: routing-engine.md
    - Limiting: limiting-cps.md
    - API: api.md
    - Logging: logging.md
    - Media Handling: media-handling.md
    - Scaling and Load Balancing: scaling-load-balancing.md 
    - Scriptforge: scriptforge.md
    - Billing: billing.md
    - Packages: packages.md
    - User Space Database: user-space-db.md
    - My Servers: my-servers.md
