site_name: ConnexCS Documentation
site_url: https://www.connexcs.com
site_description: Connex Cloud Softswitch
site_author: ConnexCS Team
google_analytics: ['UA-155210453-1', 'docs.connexcs.com']
theme:
  name: material 
  features:
    - navigation.instant
    - navigation.tabs
extra_javascript:
- extra.js
- https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
extra_css:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list

pages:
  - Cloudswitch:
    - Home: index.md
    - Getting Started: getting-started.md
    - Customer Support: reporting-problems.md
    - Video Guide: video-guide.md
    - Dashboard : dashboard.md

    - Customer:
        - Customer: customer/customer.md
        - Main: customer/main.md
        - Auth: customer/auth.md
        - Alias: customer/alias.md
        - Routing: 
            - Ingress Routing: customer/routing.md
            - CLI: customer/cli.md
        - Payment: customer/payment.md
        - Stats: customer/stats.md
        - Route Stats: customer/route-stats.md
        - Latest Calls: customer/latest-calls.md
        - Dialogs: customer/dialogs.md
        - Alerts: customer/alerts.md
        - DID: customer/did.md
        - CDR: customer/cdr.md
        - Packages: customer/package.md
        - Invoices: customer/invoices.md
        - Contracts: customer/contracts.md
        - Documents: customer/documents.md
        - Class5: customer/class5.md


    - Carrier: carrier.md
        
    - Rate Cards:
        - Rate Card Overview: rate-card-building.md
        - Provider Rate Card: provider-ratecard.md
        - Customer Rate Card: customer-ratecard.md
    
    - Voucher: voucher.md 
    
    - Routing:
        - Routing Overview: routing.md
        - Routing Strategy: routing-strategy.md
        - Routing Global: global-routing.md
        - USA Routing: routing-usa.md

    - SIP Devices: sip-devices.md
    
    - File: files.md
    
    - Circuit Test: circuit-test.md
    
    - Report: report.md  
        
    - Status: system-status.md

    - Global: global.md
    
    - Logging: logging.md
    
    - Class 5:
        - Apps: class5/apps.md
        - Conference: class5/creating-conference.md
        - IVR: class5/creating-ivr.md
        - Groups: class5/creating-group.md
        - Voicemail: class5/voicemail.md
        - Phonebook: class5/phonebook.md        
       
    - Developer:
        - Analytics: developers/analytics.md
        - Button Builder: developers/button-builder.md
        - Database: developers/database.md 
        - Form Builder: developers/form-builder.md
        - ScriptForge: developers/scriptforge.md

    - Setup:
        - AnyEdge: anyedge/anyedge.md
        - Settings:
            - Account: setup/settings/account.md
            - Payments: setup/settings/payments.md
            - Servers: setup/settings/servers.md
            - DNS: setup/settings/dns.md
            - User: setup/settings/users.md
            - Options: setup/settings/options.md
            - Data Retention: setup/settings/data-retention.md
        - Config:
            - Contracts: setup/config/contracts.md
            - Packages: setup/config/packages.md
            - Templates: setup/config/templates.md
        - Advanced:
            - Language: setup/advanced/language.md
            - Firewall: setup/advanced/firewall.md
            - Prefix Set: setup/advanced/prefix-set.md
            - Reseller Account: setup/advanced/reseller.md
            - Fraud Profile: setup/advanced/fraud.md
        - Integrations:
            - API: setup/integrations/api.md
            - Portal: setup/integrations/portal.md
            - WebPhone: setup/integrations/webphone.md
        - Information:
            - Statement: setup/information/statements.md
            - Dial Code / Destination: setup/information/dial-code-destination.md
            - Payment Log: setup/information/payment-log.md
            - Email Log: setup/information/email-log.md
            - Delay Log: setup/information/delay-log.md
            - Audit Log: setup/information/audit-log.md
            - Certificate: setup/information/certificate.md
            - Browsing Recording: setup/information/recording.md
            - Jobs: setup/information/jobs.md

    - Architecture:
        - API: api.md
        - NAT Traversal: far-end-nat-traversal.md
        - Security: security.md
        - Media Handling: media-handling.md
        - Scaling and Load Balancing: scaling-load-balancing.md
        - Specification: spec.md        

    - Topical Guides:
        - ConnexCS Basics: basics-guide.md
        - Billing: billing-guide.md
        - Customer Documents: doc-guide.md
        - Monitoring: monitoring.md
        - Troubleshooting: tshoot-guide.md
        
    - Miscellaneous:
        - Acronyms and Definitions: acronyms-and-definitions.md
        - Connex Billing: billing.md
        - Calling Card: calling-card.md       
        - Capacity Limiting: limiting-cps.md
        - Credit Control: credit-control.md
        - Do Not Call lists: dnc.md
        - Feature List: feature-list.md
        - Number Manipulation: number-manipulation.md
        - Changing Language: changing-language.md
        - Changing Password: changing-password.md
        - Logging Out: logging-out.md

  - Customer Portal:
    - Guides: customer-portal/customer-portal.md
    - Dashboard: customer-portal/dashboard.md
    - CDR: customer-portal/cdr.md
    - Breakout: customer-portal/breakout.md
    - Authentication: customer-portal/authentication.md
    - DID: customer-portal/did.md
    - CLI: customer-portal/cli.md
    - Latest Calls: customer-portal/latest-calls.md
    - Failover: customer-portal/failover.md
    - Setup: customer-portal/setup.md
    - Payment: customer-portal/payment.md
    - Routes: customer-portal/routes.md
    - Interconnect: customer-portal/interconnect.md

  - WebPhone: 
    - WebPhone: setup/integrations/webphone.md
